version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.15
  prometheus: prometheus/prometheus@0.11.0
executors:
  shellcheck:
    docker:
      - image: koalaman/shellcheck
  python:
    docker:
      - image: cimg/python:3.9
jobs:
  flake8_lint:
    executor: python
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
workflows:
  version: 2
  scripts:
    jobs:
      - shellcheck/check
      - flake8_lint
